numero = input('DIGITE UM NUMERO DE QUATRO DIGITOS DE 0 A 9999: ')
print('O milhar é {}'.format(numero[0]))
print('A centena é {}'.format(numero[1]))
print('A Dezena é {}'.format(numero[2]))
print('A unidade é {}'.format(numero[3]))