tabela = ('Corinthians', 'Palmeiras', 'São Paulo', 'Santos', 'Flamengo', 'Vasco','Fluminense', 'Botafogo','Gremio','Inter')
print('-=' *15)
print(f'Os quatros primeiros que vão para a libertadores são {tabela[:4]}')
print('-=' *15)
print(f'Os rebaixados são {tabela[-4:]}')
print('-=' *15)
print(f'Ordem alfabetica {sorted(tabela)}')
print('-=' *15)
print(f'O Fluminense está na posição {tabela.index("Fluminense")+1} na tabela do brasileiro')